const APP_VERSION = 'тест.01.05';
const CACHE_VERSION = 'v.тест.01.05';
const DATA_VERSION = "тест.01.05";

const ENCRYPTED_CONTACTS_LEVEL3 = "";
const ENCRYPTED_STATIONS_LEVEL3 = "";
const ENCRYPTED_PARKING_LEVEL3 = "";
const ENCRYPTED_DOCUMENTS_LEVEL3 = "";

const ENCRYPTED_CONTACTS_LEVEL2 = "";
const ENCRYPTED_STATIONS_LEVEL2 = "";
const ENCRYPTED_PARKING_LEVEL2 = "";

const ENCRYPTED_CONTACTS_LEVEL1 = "";
const ENCRYPTED_PARKING_LEVEL1 = "";
